/**
 * PARTY PEOPLE MODEL
 * AGENT
 * THIRSTINESS
 * COMPATIBILITY{LETS SAY WE HAVE PEOPLE FROM 10 NEIGHBOURHOODS THE PEOPLE FROM
 * THE SAME HOOD ARE 100% COMPATIBLE AND IT DECREASES ACCORDING TO THE DISTANCE
 * FROM THAT NEIGHBOURHOOD, THIS INFLUENCES HOW MUCH TIME THEY SPEND TALKING TO EACH OTHER}
 * 
 * WHEN THIRSTINESS REACHES 0 THE AGENT GOES TO THE BAR TO REFILL HIS DRINK.
 * ON THE WAY BACK IT STOPS TO THE CLOSEST AGENT WITH HIGHER COMPATIBILITY. 
 * THEREFORE IF THE AGENT HAS TO CHOOSE BETWEEN AN AGENT WITH COMPATIBILITY
 * 10 AT DISTANCE 10 AND ANOTHER ONE WITH COMPATIBILITY 50 AT DISTANCE 20 WILL
 * GO TO THE SECOND ONE.
 * 
 * BAR
 * WHERE AGENTS SOOTH THEIR THIRSTINESS
 */
Party p;
int alpha = 255;
void setup() {
  size(800, 800);
  p = new Party(300, 3);
  background(0);
  smooth();
}
void draw() {
  fill(0, alpha);
  rect(0, 0, width, height);
  //background(0);
  p.update();
  p.show();
}